baseURL = "https://netarchitect.cloud/"
languageCode = "fr"
title = "Net Architect"
theme = ["github.com/chipzoller/hugo-clarity"]
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/chipzoller/hugo-clarity"

[params]
  enableSearch = true
  dateFormat = "02 January 2006"
  description = "Blog technique sobre et élégant par Kevin Allioli"
  author = "Kevin Allioli"
  darkMode = true
  showReadingTime = false
  showToc = true
  codeLineNumbers = true
  
  comments = true
  giscus = true
  giscusRepo = "Net-Architect-Cloud/website"
  giscusRepoId = "R_kgDOO_9SBA"
  giscusCategory = "Comments"
  giscusCategoryId = "DIC_kwDOO_9SBM4Cr8ZL"
  giscusMapping = "pathname"
  giscusReactionsEnabled = "0"
  giscusTheme = "cobalt"
  giscusLang = "fr"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "monokai"
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 10