[[main]]
  name = "Accueil"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "posts/"
  weight = -109

[[main]]
  name = "À propos"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/Net-Architect-Cloud"
[[social]]
  name = "linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/kevin-allioli"
[[social]]
  name = "rss"
  weight = 3
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
# name = "bluesky"
# url = "https://bsky.app/profile/#"
